### ISSUE TITLE
Establish routines for testing

### ISSUE THREAD

**Issue by RuneThe** [inf112-v19/Bender#19]
Details for each area, good routines, special and standard tests.

**Comment by petterdaae** [comment]
Do you mean like the development process? How to use git etc.?
We should definitely discuss testing routines.

**Comment by RuneThe** [comment]
Thinking to make tests for vital parts, so furher work is easier to manage for others, and original ideas and functionality is maintained after updates and exdended functionality. Maybe set a milestone, and make plain tests and some randomized tests to assure functionality within the frame we consider necessary, before extending functionality.
