### ISSUE TITLE
Create move robot functionality

### ISSUE THREAD

**Issue by petterdaae** [inf112-v19/Bender#37]

**Comment by petterdaae** [comment]
@AndreasCanAtakan it's correct that these methods should be in the tiles and robot classes right?

**Comment by RuneThe** [comment]
Discussed and found that board would be best to have moving the robots. Robots is now only knows where it is heading. But you have other ideas?

**Comment by petterdaae** [comment]
I thought that the board might call a move method on the robots @RuneThe

**Comment by RuneThe** [comment]
Andreas had the idea, that each tile knows is neighbours and can reply to board if the requested movement is legal and can be made, and connected tiles is updated in board, and in each of the tiles involved.  Board also reflect what is output in the graphics class. This way all details  of complete board and interaction is kept within 2 classes. But I think we need to discuss further and decide which strategy to use.

**Comment by AndreasCanAtakan** [comment]
@RuneThe I agree, I think it would be most practical to keep the interaction within the two classes. This is a good topic for discussion this coming thursday.
