### ISSUE TITLE
Tiles (To be splitted, ref #60)

### ISSUE THREAD

**Issue by petterdaae** [inf112-v19/Bender#6]

**Comment by RuneThe** [comment]
Started to implement connections with robots and board

**Comment by RuneThe** [comment]
This task should be splitted into several smaller tasks. 
@AndreasCanAtakan, will you look into this and suggest?
OF course I will also take part in discussing ;-D

**Comment by AndreasCanAtakan** [comment]
@RuneThe You are right, this is something I will have to look into :)
